#server:
#  port: 8080
#
#spring:
#  application:
#    name: gateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: patient-service
#          uri: http://localhost:8081
#          predicates:
#            - Path=/patients/**
#
#          filters:
#           - RewritePath=/patients(?<segment>.*), /patients${segment}
#spring:
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: patient-service
#              uri: http://localhost:8082
#              predicates:
#                - Path=/patients/**

server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-service
              uri: http://localhost:8081
              predicates:
                - Path=/patients/**


