
server:
  port: 8080

spring:
  application:
        name: gateway-service
  cloud:
    gateway:
#      server:
#        webflux:
      routes:
        - id: patient-service
          uri: http://patient-service:8081
          predicates:
            - Path=/patients/**
        #              filters:
        #                - RewritePath=/patients/(?<segment>.*), /patients/${segment}
        - id: patient-images
          uri: http://patient-service:8081
          predicates:
            - Path=/images/**

        - id: front
          uri: http://front:8082
          predicates:
            - Path=/front/**
        #              filters:
        #                - RewritePath=/front/(?<segment>.*), /${segment}

        - id: notes-service
          uri: http://notes-service:8083
          predicates:
            - Path=/notes/**
          filters:
            - RewritePath=/notes/(?<segment>.*), /notes/${segment}

        - id: risk-service
          uri: http://diabetes-risk-service:8084
          predicates:
            - Path=/risk/**
          filters:
            - RewritePath=/risk/(?<segment>.*), /risk/${segment}
